SELECT
    SCIENTIFIC_FIELD.FIELD_NAME,
    COUNT(DISTINCT PROJECT_FIELD.PROJECT_ID) AS PROJECT_COUNT
FROM SCIENTIFIC_FIELD, PROJECT_FIELD
WHERE SCIENTIFIC_FIELD.FIELD_ID = PROJECT_FIELD.FIELD_ID
GROUP BY SCIENTIFIC_FIELD.FIELD_NAME
ORDER BY PROJECT_COUNT DESC;

SELECT
    PROJECT.PROJECT_ID,
    PROJECT.TITLE,
    SUM(EXPENSE.AMOUNT) AS TOTAL_EXPENSES
FROM PROJECT, EXPENSE
WHERE PROJECT.PROJECT_ID = EXPENSE.PROJECT_ID
GROUP BY PROJECT.PROJECT_ID, PROJECT.TITLE
HAVING SUM(EXPENSE.AMOUNT) > 70000
ORDER BY TOTAL_EXPENSES DESC;

SELECT
    PROJECT_ID,
    SUM(AMOUNT) AS TOTAL_PAYMENTS
FROM INCOMING_PAYMENT
GROUP BY PROJECT_ID;

SELECT
    P.PROJECT_ID,
    P.TITLE,
    SUM(E.AMOUNT) AS TOTAL_EXPENSE
FROM PROJECT P, EXPENSE E
WHERE P.PROJECT_ID = E.PROJECT_ID
GROUP BY P.PROJECT_ID, P.TITLE;

SELECT
    PROJECT_ID,
    COUNT(MEMBER_ID) AS NUMBER_OF_MEMBERS
FROM TEAM_ASSIGNMENT
GROUP BY PROJECT_ID;

SELECT
    M.MEMBER_ID,
    M.FULL_NAME,
    M.MEMBER_TYPE AS ROLE,
    P.PROJECT_ID,
    P.TITLE AS PROJECT_TITLE,
    TA.EFFORT
FROM MEMBER M, TEAM_ASSIGNMENT TA, PROJECT P
WHERE M.MEMBER_ID = TA.MEMBER_ID
  AND TA.PROJECT_ID = P.PROJECT_ID
ORDER BY P.PROJECT_ID, M.MEMBER_ID;


SELECT
    PROJECT_ID,
    MIN(DUE_DATE) AS EARLIEST_DUE_DATE,
    MAX(DUE_DATE) AS LATEST_DUE_DATE
FROM DELIVERABLE
GROUP BY PROJECT_ID;

SELECT
    MEMBER_ID,
    COUNT(PROJECT_ID) AS PROJECT_COUNT
FROM TEAM_ASSIGNMENT
GROUP BY MEMBER_ID
HAVING COUNT(PROJECT_ID) >= 2;

SELECT
    MEMBER_ID,
    COUNT(PROJECT_ID) AS PROJECT_COUNT
FROM TEAM_ASSIGNMENT
GROUP BY MEMBER_ID
HAVING COUNT(PROJECT_ID) >= 2;

SELECT
    PROJECT_ID,
    AVG(AMOUNT) AS AVG_MONTHLY_EXPENSE
FROM EXPENSE
GROUP BY PROJECT_ID
HAVING AVG(AMOUNT) > 50000;