--
-- File generated with SQLiteStudio v3.4.18 on Cum Mar 6 00:20:22 2026
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: DELIVERABLE
CREATE TABLE IF NOT EXISTS DELIVERABLE (
    DELIVERABLE_ID   INTEGER PRIMARY KEY,
    DELIVERABLE_TYPE TEXT,         -- report / paper / software ...
    TITLE            TEXT NOT NULL,
    DUE_DATE         DATE,
    SUBMISSION_DATE  DATE,
    APPROVAL_STATUS  TEXT,         -- submitted / approved / rejected ...
    FUNDER_CODE      TEXT,         -- funder’ýn sistemindeki kod
    PROJECT_ID       INTEGER NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID)
);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (1, 'Progress Report', 'Year 1 Progress Report - AI Mobility', '2025-01-31', '2025-01-28', 'Approved', 'PR1-AI-MOB', 1);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (2, 'Final Report', 'Final Technical Report - Green Campus Energy', '2025-08-31', NULL, 'In Preparation', 'FR-GREEN-ENERGY', 2);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (3, 'Journal Paper', 'Deep Learning for Micro-Mobility Pattern Mining', '2025-06-30', NULL, 'Planned', 'JP-AI-MOB-01', 1);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (4, 'Software', 'Energy Dashboard Prototype', '2024-12-31', '2024-12-20', 'Submitted', 'SW-GREEN-01', 2);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (5, 'Progress Report', 'Bioinformatics Year 1 Report', '2025-03-01', NULL, 'Pending', 'BIO-Y1', 3);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (6, 'Software', 'Autonomous Drone Navigation Module', '2024-08-30', '2024-08-25', 'Approved', 'ROB-DRONE-01', 4);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (7, 'Journal Paper', 'Deep Reinforcement Learning for Disaster Robotics', '2025-12-31', NULL, 'In Writing', 'ROB-DL-PAPER', 4);
INSERT INTO DELIVERABLE (DELIVERABLE_ID, DELIVERABLE_TYPE, TITLE, DUE_DATE, SUBMISSION_DATE, APPROVAL_STATUS, FUNDER_CODE, PROJECT_ID) VALUES (8, 'Technical Report', 'AI Threat Detection System Architecture', '2025-11-15', NULL, 'Pending', 'AI-SEC-ARCH', 5);

-- Table: EXPENSE
CREATE TABLE IF NOT EXISTS EXPENSE (
    EXPENSE_ID    INTEGER PRIMARY KEY,
    EXPENSE_DATE  DATE NOT NULL,
    AMOUNT        REAL NOT NULL,
    EXPENSE_TYPE  TEXT,       -- salary / equipment / travel ...
    DESCRIPTION   TEXT,
    VENDOR        TEXT,
    PROJECT_ID    INTEGER NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID)
);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (1, '2024-02-01', 60000.0, 'Salary', 'Researcher salaries for January 2024', 'KHAS Payroll', 1);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (2, '2024-03-10', 120000.0, 'Equipment', 'GPU server purchase', 'ABC Tech Ltd.', 1);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (3, '2023-11-05', 30000.0, 'Travel', 'Conference travel to IEEE SmartGrid', 'TravelCo', 2);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (4, '2024-01-12', 45000.0, 'Equipment', 'Smart meters and sensors', 'GreenEnergy Equip.', 2);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (5, '2024-04-15', 85000.0, 'Lab Equipment', 'Genome sequencer upgrade', 'BioTech Labs', 3);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (6, '2024-05-20', 45000.0, 'Software', 'Robotics simulation software licenses', 'SimuRobotics', 4);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (7, '2023-12-10', 25000.0, 'Travel', 'Robotics conference presentation', 'GlobalTravel', 4);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (8, '2024-10-15', 30000.0, 'Salary', 'AI researcher salary', 'KHAS Payroll', 5);
INSERT INTO EXPENSE (EXPENSE_ID, EXPENSE_DATE, AMOUNT, EXPENSE_TYPE, DESCRIPTION, VENDOR, PROJECT_ID) VALUES (9, '2024-11-01', 15000.0, 'Cloud Services', 'AI training environment costs', 'Azure', 5);

-- Table: FUNDING_BODY
CREATE TABLE IF NOT EXISTS FUNDING_BODY (
    FUNDING_BODY_ID   INTEGER PRIMARY KEY,
    NAME              TEXT NOT NULL,
    COUNTRY           TEXT,
    TYPE              TEXT,
    CONTACT_EMAIL     TEXT,
    CONTACT_PHONE     TEXT
);
INSERT INTO FUNDING_BODY (FUNDING_BODY_ID, NAME, COUNTRY, TYPE, CONTACT_EMAIL, CONTACT_PHONE) VALUES (1, 'TUBITAK', 'Turkey', 'National Agency', 'info@tubitak.gov.tr', '+90-312-000-0000');
INSERT INTO FUNDING_BODY (FUNDING_BODY_ID, NAME, COUNTRY, TYPE, CONTACT_EMAIL, CONTACT_PHONE) VALUES (2, 'European Commission - Horizon Europe', 'Belgium', 'EU Programme', 'research@ec.europa.eu', '+32-2-000-0000');
INSERT INTO FUNDING_BODY (FUNDING_BODY_ID, NAME, COUNTRY, TYPE, CONTACT_EMAIL, CONTACT_PHONE) VALUES (3, 'British Council Research Fund', 'UK', 'International', 'bc.research@britishcouncil.org', '+44-20-1234-5678');
INSERT INTO FUNDING_BODY (FUNDING_BODY_ID, NAME, COUNTRY, TYPE, CONTACT_EMAIL, CONTACT_PHONE) VALUES (4, 'KHAS Internal Research Fund', 'Turkey', 'University Fund', 'khas.research@khas.edu.tr', '+90-212-123-4567');

-- Table: INCOMING_PAYMENT
CREATE TABLE IF NOT EXISTS INCOMING_PAYMENT (
    PAYMENT_ID      INTEGER PRIMARY KEY,
    AMOUNT          REAL NOT NULL,
    PAYMENT_DATE    DATE NOT NULL,
    INSTALLMENT_NO  INTEGER,
    REFERENCE_CODE  TEXT,
    NOTES           TEXT,
    PROJECT_ID      INTEGER NOT NULL,
    FUNDING_BODY_ID INTEGER NOT NULL,
    FOREIGN KEY (PROJECT_ID)      REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (FUNDING_BODY_ID) REFERENCES FUNDING_BODY(FUNDING_BODY_ID)
);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (1, 250000.0, '2024-01-15', 1, 'TUB-2024-001', 'Initial advance payment', 1, 1);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (2, 150000.0, '2025-01-20', 2, 'TUB-2025-001', 'Second instalment after first-year report', 1, 1);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (3, 200000.0, '2023-09-15', 1, 'EU-HE-ENERGY-01', 'Initial grant payment', 2, 2);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (4, 150000.0, '2024-09-20', 2, 'EU-HE-ENERGY-02', 'Second instalment after mid-term review', 2, 2);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (5, 200000.0, '2024-04-10', 1, 'BC-2024-BIO-01', 'Initial payment for bioinformatics project', 3, 3);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (6, 150000.0, '2024-10-05', 2, 'BC-2024-BIO-02', 'Second milestone payment', 3, 3);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (7, 300000.0, '2023-06-01', 1, 'TUB-ROB-01', 'Robotics project funding', 4, 1);
INSERT INTO INCOMING_PAYMENT (PAYMENT_ID, AMOUNT, PAYMENT_DATE, INSTALLMENT_NO, REFERENCE_CODE, NOTES, PROJECT_ID, FUNDING_BODY_ID) VALUES (8, 120000.0, '2024-09-01', 1, 'KHAS-AI-01', 'Internal AI grant release', 5, 4);

-- Table: MEMBER
CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID   INTEGER PRIMARY KEY,
    FULL_NAME   TEXT NOT NULL,
    MEMBER_TYPE TEXT NOT NULL,   -- professor / postdoc / PhD student ...
    DEPARTMENT  TEXT,
    EMAIL       TEXT,
    TEAM_ID     INTEGER          -- ana takýmý göstermek için; FK tanýmlamadýk
    -- FOREIGN KEY (TEAM_ID) REFERENCES PROJECT_TEAM(TEAM_ID)
);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (1, 'Prof. Ayse Yilmaz', 'Professor', 'Computer Engineering', 'ayse.yilmaz@khas.edu.tr', 5);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (2, 'Prof. Mehmet Demir', 'Professor', 'Electrical-Electronics', 'mehmet.demir@khas.edu.tr', 2);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (3, 'Dr. Elif Kaya', 'Postdoc', 'Computer Engineering', 'elif.kaya@khas.edu.tr', 1);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (4, 'Ali Can', 'PhD Student', 'Computer Engineering', 'ali.can@khas.edu.tr', 1);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (5, 'Dr. Zeynep Arslan', 'Postdoc', 'Bioinformatics', 'zeynep.arslan@khas.edu.tr', 3);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (6, 'Mert Aksoy', 'PhD Student', 'Energy Systems', 'mert.aksoy@khas.edu.tr', NULL);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (7, 'Prof. Selim Tan', 'Professor', 'Computer Engineering', 'selim.tan@khas.edu.tr', 5);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (8, 'Ayþe Nur Karaca', 'PhD Student', 'Electrical Engineering', 'aysenur.karaca@khas.edu.tr', 4);
INSERT INTO MEMBER (MEMBER_ID, FULL_NAME, MEMBER_TYPE, DEPARTMENT, EMAIL, TEAM_ID) VALUES (9, 'Dr. Cenk Aydin', 'Postdoc', 'Robotics', 'cenk.aydin@khas.edu.tr', 4);

-- Table: PROJECT
CREATE TABLE IF NOT EXISTS PROJECT (
    PROJECT_ID      INTEGER PRIMARY KEY,
    TITLE           TEXT NOT NULL,
    TOTAL_BUDGET    REAL,
    STARTDATE       DATE,
    ENDDATE         DATE,
    STATUS          TEXT,           -- planned / active / completed ...
    FUNDINGBODY_ID  INTEGER NOT NULL,
    COORDINATOR_ID  INTEGER NOT NULL,
    FOREIGN KEY (FUNDINGBODY_ID) REFERENCES FUNDING_BODY(FUNDING_BODY_ID),
    FOREIGN KEY (COORDINATOR_ID) REFERENCES PROJECT_COORDINATOR(COORDINATOR_ID)
);
INSERT INTO PROJECT (PROJECT_ID, TITLE, TOTAL_BUDGET, STARTDATE, ENDDATE, STATUS, FUNDINGBODY_ID, COORDINATOR_ID) VALUES (1, 'AI-based Urban Mobility Analytics', 750000.0, '2024-01-01', '2026-12-31', 'Active', 1, 1);
INSERT INTO PROJECT (PROJECT_ID, TITLE, TOTAL_BUDGET, STARTDATE, ENDDATE, STATUS, FUNDINGBODY_ID, COORDINATOR_ID) VALUES (2, 'Sustainable Campus Energy Optimization', 500000.0, '2023-09-01', '2025-08-31', 'Active', 2, 2);
INSERT INTO PROJECT (PROJECT_ID, TITLE, TOTAL_BUDGET, STARTDATE, ENDDATE, STATUS, FUNDINGBODY_ID, COORDINATOR_ID) VALUES (3, 'Bioinformatics Pipeline for Cancer Research', 650000.0, '2024-03-01', '2027-02-28', 'Active', 3, 4);
INSERT INTO PROJECT (PROJECT_ID, TITLE, TOTAL_BUDGET, STARTDATE, ENDDATE, STATUS, FUNDINGBODY_ID, COORDINATOR_ID) VALUES (4, 'Robotics for Disaster Response', 900000.0, '2023-05-15', '2026-05-15', 'Active', 1, 3);
INSERT INTO PROJECT (PROJECT_ID, TITLE, TOTAL_BUDGET, STARTDATE, ENDDATE, STATUS, FUNDINGBODY_ID, COORDINATOR_ID) VALUES (5, 'AI-based Cyber Threat Detection', 350000.0, '2024-09-01', '2026-09-01', 'Planned', 4, 1);

-- Table: PROJECT_COORDINATOR
CREATE TABLE IF NOT EXISTS PROJECT_COORDINATOR (
    COORDINATOR_ID   INTEGER PRIMARY KEY,
    OFFICE_ROOM      TEXT,
    PHONE_EXTENSION  TEXT,
    MEMBER_ID        INTEGER NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);
INSERT INTO PROJECT_COORDINATOR (COORDINATOR_ID, OFFICE_ROOM, PHONE_EXTENSION, MEMBER_ID) VALUES (1, 'F-305', '1205', 1);
INSERT INTO PROJECT_COORDINATOR (COORDINATOR_ID, OFFICE_ROOM, PHONE_EXTENSION, MEMBER_ID) VALUES (2, 'D-210', '1187', 2);
INSERT INTO PROJECT_COORDINATOR (COORDINATOR_ID, OFFICE_ROOM, PHONE_EXTENSION, MEMBER_ID) VALUES (3, 'E-110', '1199', 7);
INSERT INTO PROJECT_COORDINATOR (COORDINATOR_ID, OFFICE_ROOM, PHONE_EXTENSION, MEMBER_ID) VALUES (4, 'R-220', '1312', 5);

-- Table: PROJECT_FIELD
CREATE TABLE IF NOT EXISTS PROJECT_FIELD (
    PROJECT_ID  INTEGER NOT NULL,
    FIELD_ID    INTEGER NOT NULL,
    PRIMARY KEY (PROJECT_ID, FIELD_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (FIELD_ID)   REFERENCES SCIENTIFIC_FIELD(FIELD_ID)
);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (1, 1);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (1, 3);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (2, 2);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (3, 4);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (3, 3);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (4, 6);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (4, 5);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (5, 1);
INSERT INTO PROJECT_FIELD (PROJECT_ID, FIELD_ID) VALUES (5, 5);

-- Table: PROJECT_TEAM
CREATE TABLE IF NOT EXISTS PROJECT_TEAM (
    TEAM_ID        INTEGER PRIMARY KEY,
    TEAM_NAME      TEXT NOT NULL,
    NOTES          TEXT,
    PROJECT_ID     INTEGER NOT NULL,
    COORDINATOR_ID INTEGER NOT NULL,
    FOREIGN KEY (PROJECT_ID)     REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (COORDINATOR_ID) REFERENCES PROJECT_COORDINATOR(COORDINATOR_ID)
);
INSERT INTO PROJECT_TEAM (TEAM_ID, TEAM_NAME, NOTES, PROJECT_ID, COORDINATOR_ID) VALUES (1, 'AI Mobility Core Team', 'Main research group for mobility analytics', 1, 1);
INSERT INTO PROJECT_TEAM (TEAM_ID, TEAM_NAME, NOTES, PROJECT_ID, COORDINATOR_ID) VALUES (2, 'Green Campus Energy Team', 'Energy optimization team', 2, 2);
INSERT INTO PROJECT_TEAM (TEAM_ID, TEAM_NAME, NOTES, PROJECT_ID, COORDINATOR_ID) VALUES (3, 'Bioinformatics Research Group', 'Cancer genomics subgroup', 3, 4);
INSERT INTO PROJECT_TEAM (TEAM_ID, TEAM_NAME, NOTES, PROJECT_ID, COORDINATOR_ID) VALUES (4, 'Disaster Robotics Team', 'Humanoid + drone systems', 4, 3);
INSERT INTO PROJECT_TEAM (TEAM_ID, TEAM_NAME, NOTES, PROJECT_ID, COORDINATOR_ID) VALUES (5, 'AI Threat Detection Team', 'Security & AI research', 5, 1);

-- Table: SCIENTIFIC_FIELD
CREATE TABLE IF NOT EXISTS SCIENTIFIC_FIELD (
    FIELD_ID        INTEGER PRIMARY KEY,
    FIELD_NAME      TEXT NOT NULL,
    DESCRIPTION     TEXT
);
INSERT INTO SCIENTIFIC_FIELD (FIELD_ID, FIELD_NAME, DESCRIPTION) VALUES (1, 'Artificial Intelligence', 'Machine learning, deep learning and intelligent systems');
INSERT INTO SCIENTIFIC_FIELD (FIELD_ID, FIELD_NAME, DESCRIPTION) VALUES (2, 'Sustainable Energy', 'Renewable energy, smart grids and efficiency');
INSERT INTO SCIENTIFIC_FIELD (FIELD_ID, FIELD_NAME, DESCRIPTION) VALUES (3, 'Data Science', 'Data analytics, big data and visualization');
INSERT INTO SCIENTIFIC_FIELD (FIELD_ID, FIELD_NAME, DESCRIPTION) VALUES (4, 'Bioinformatics', 'Genomics, proteomics and computational biology');
INSERT INTO SCIENTIFIC_FIELD (FIELD_ID, FIELD_NAME, DESCRIPTION) VALUES (5, 'Cybersecurity', 'Network security, cryptography');
INSERT INTO SCIENTIFIC_FIELD (FIELD_ID, FIELD_NAME, DESCRIPTION) VALUES (6, 'Robotics', 'Automation, control systems, humanoid robotics');

-- Table: TEAM_ASSIGNMENT
CREATE TABLE IF NOT EXISTS TEAM_ASSIGNMENT (
    ASSIGNMENT_ID INTEGER PRIMARY KEY,
    START_DATE    DATE NOT NULL,
    END_DATE      DATE,
    NOTES         TEXT,
    TEAM_ID       INTEGER NOT NULL,
    PROJECT_ID    INTEGER NOT NULL,
    MEMBER_ID     INTEGER NOT NULL, EFFORT TEXT,
    FOREIGN KEY (TEAM_ID)    REFERENCES PROJECT_TEAM(TEAM_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (MEMBER_ID)  REFERENCES MEMBER(MEMBER_ID)
);
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (1, '2024-01-01', NULL, 'PI of the project', 1, 1, 1, 'full-time');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (2, '2024-02-01', NULL, 'Postdoc, full-time', 1, 1, 3, 'part-time');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (3, '2024-02-15', NULL, 'PhD student, 50% workload', 1, 1, 4, '50%');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (4, '2023-09-01', NULL, 'PI of the project', 2, 2, 2, 'full-time');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (5, '2023-10-01', NULL, 'Postdoc, shared', 2, 2, 3, 'part-time');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (6, '2024-03-01', NULL, 'Lead bioinformatics researcher', 3, 3, 5, 'full-time');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (7, '2024-04-01', NULL, 'Genome data analyst', 3, 3, 3, 'part-time');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (8, '2023-05-15', NULL, 'Robotics control engineer', 4, 4, 9, '20 hours/week');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (9, '2023-07-01', NULL, 'Drone software developer', 4, 4, 8, '20 hours/week');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (10, '2024-09-10', NULL, 'Cybersecurity AI modeller', 5, 5, 7, '20 hours/week');
INSERT INTO TEAM_ASSIGNMENT (ASSIGNMENT_ID, START_DATE, END_DATE, NOTES, TEAM_ID, PROJECT_ID, MEMBER_ID, EFFORT) VALUES (11, '2024-09-20', NULL, 'ML researcher (part-time)', 5, 5, 1, '50%');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
